### ISSUE TITLE
API for shift types

### ISSUE THREAD

**Issue by johnjohndoe** [engelsystem/engelsystem#1104]
As far as I understand shift types can be created and changed at any time in an Engelsystem instance.

The shifts JSON currently exposes the IDs of shift types `shifttype_id` as integers.

Is there an API for the human readable shift type names or plans to integrate them in the shifts JSON response?

**Comment by MyIgel** [comment]
The current "API" is defined in `$data` in https://github.com/engelsystem/engelsystem/blob/main/src/Controllers/FeedController.php#L71 (extracted from what the Fahrplan app uses or at least what i found that it uses) all other values might change at any time as they are just added for convenience  (and if the type is wrong i should fix it)^^
(and if you need the name i can add that to the export)

I can add more fields there but on the long run a dedicated Fahrplan export / endpoint(s) might be the better option.

At the moment there is no other dedicated API but it will be at some point, i created https://github.com/engelsystem/engelsystem/issues/1105 to collect requirements.

**Comment by johnjohndoe** [comment]
Ah. Interesting. I never look the `FeedController` code up - thank you for the reference.

I think I am still missing knowledge of typical use cases of Engelsystem users to design a good API. I would appreciate a virtual tour at some point.

This recent request originates from the wish to see the shift types in the Android app. I never thought about in depth and what information is hidden there. I saw it has a name and a description.

**Comment by MyIgel** [comment]
@johnjohndoe i can add it too (esp. as it contains useful information that might describe tasks better) & sure, just say when and we can do a BBB/Jitsi/whatever session :)

**Comment by johnjohndoe** [comment]
@MyIgel Did you have time to extend the JSON to include the name and description of a shift type?

**Comment by MyIgel** [comment]
Thats a great question, PR incoming ^^
(I will also add a `link` field there where a user can find a URL to the shift, might be useful too)

**Comment by xuwhite** [comment]
Ugly but works

**Comment by MyIgel** [comment]
Hi @johnjohndoe, its now merged too ^^
